### ISSUE TITLE
B004FTMV18 fails to decrypt when rebuild chapters set

### ISSUE THREAD

**Issue by PurpleBooth** [mkb79/audible-cli#99] opened 2022-06-22 06:46 UTC
ffmpeg reports "could not allocate memory", but that's a bit of a red herring as it reports that for lots of things, including misconfiguration. Without the ".new.meta" chapter information the file decrypts fine (I tested this manually using the same command).

Maybe somethng to do with the format of the file?

**Comment by mkb79** [comment] 2022-06-22 06:57
Maybe the issue is related with new [sub chapters](https://github.com/rmcrackan/Libation/issues/278)? Have the new meta file such sub chapters?

**Comment by PurpleBooth** [comment] 2022-06-22 07:21
Is there a command I can run to get that output? I am not familiar with the API

**Comment by PurpleBooth** [comment] 2022-06-22 07:50
I will take a look at this tomorrow, going to be busy the rest of the day. I have posted over in discussions a little about my setup https://github.com/mkb79/audible-cli/discussions/100. Not sure if that helps.

**Comment by PurpleBooth** [comment] 2022-06-22 11:49
```
;FFMETADATA1
major_brand=aax 
minor_version=1
compatible_brands=aax M4B mp42isom
date=2010
comment=Chapter 51
title=The Many-Colored Land: Volume 1 of the Saga of Pliocene Exile
artist=Julian May
album_artist=Julian May
album=The Many-Colored Land: Volume 1 of the Saga of Pliocene Exile
genre=Audiobook
copyright=©1981 Julian May (P)2010 Blackstone Audio, Inc.
encoder=Lavf59.16.100
[CHAPTER]
TIMEBASE=1/44100
START=0
END=25148416
title=Chapter 1
[CHAPTER]
TIMEBASE=1/44100
START=25148416
END=39164928
title=Chapter 2
[CHAPTER]
TIMEBASE=1/44100
START=39164928
END=83675136
title=Chapter 3
[CHAPTER]
TIMEBASE=1/44100
START=83675136
END=110763008
title=Chapter 4
[CHAPTER]
TIMEBASE=1/44100
START=110763008
END=150396928
title=Chapter 5
[CHAPTER]
TIMEBASE=1/44100
START=150396928
END=178080768
title=Chapter 6
[CHAPTER]
TIMEBASE=1/44100
START=178080768
END=200075264
title=Chapter 7
[CHAPTER]
TIMEBASE=1/44100
START=200075264
END=217696256
title=Chapter 8
[CHAPTER]
TIMEBASE=1/44100
START=217696256
END=233501696
title=Chapter 9
[CHAPTER]
TIMEBASE=1/44100
START=233501696
END=294145024
title=Chapter 10
[CHAPTER]
TIMEBASE=1/44100
START=294145024
END=352421888
title=Chapter 11
[CHAPTER]
TIMEBASE=1/44100
START=352421888
END=381885440
title=Chapter 12
[CHAPTER]
TIMEBASE=1/44100
START=381885440
END=392193024
title=Chapter 13
[CHAPTER]
TIMEBASE=1/44100
START=392193024
END=436666368
title=Chapter 14
[CHAPTER]
TIMEBASE=1/44100
START=436666368
END=452639744
title=Chapter 15
[CHAPTER]
TIMEBASE=1/44100
START=452639744
END=497457152
title=Chapter 16
[CHAPTER]
TIMEBASE=1/44100
START=497457152
END=520668160
title=Chapter 17
[CHAPTER]
TIMEBASE=1/44100
START=520668160
END=533898240
title=Chapter 18
[CHAPTER]
TIMEBASE=1/44100
START=533898240
END=566441984
title=Chapter 19
[CHAPTER]
TIMEBASE=1/44100
START=566441984
END=597669888
title=Chapter 20
[CHAPTER]
TIMEBASE=1/44100
START=597669888
END=648133632
title=Chapter 21
[CHAPTER]
TIMEBASE=1/44100
START=648133632
END=682863616
title=Chapter 22
[CHAPTER]
TIMEBASE=1/44100
START=682863616
END=733511680
title=Chapter 23
[CHAPTER]
TIMEBASE=1/44100
START=733511680
END=780257280
title=Chapter 24
[CHAPTER]
TIMEBASE=1/44100
START=780257280
END=824526848
title=Chapter 25
[CHAPTER]
TIMEBASE=1/44100
START=824526848
END=855089152
title=Chapter 26
[CHAPTER]
TIMEBASE=1/44100
START=855089152
END=897764352
title=Chapter 27
[CHAPTER]
TIMEBASE=1/44100
START=897764352
END=971331584
title=Chapter 28
[CHAPTER]
TIMEBASE=1/44100
START=971331584
END=1039423488
title=Chapter 29
[CHAPTER]
TIMEBASE=1/44100
START=1039423488
END=1077112832
title=Chapter 30
[CHAPTER]
TIMEBASE=1/44100
START=1077112832
END=1132003328
title=Chapter 31
[CHAPTER]
TIMEBASE=1/44100
START=1132003328
END=1197390848
title=Chapter 32
[CHAPTER]
TIMEBASE=1/44100
START=1197390848
END=1268199424
title=Chapter 33
[CHAPTER]
TIMEBASE=1/44100
START=1268199424
END=1337348096
title=Chapter 34
[CHAPTER]
TIMEBASE=1/44100
START=1337348096
END=1420164096
title=Chapter 35
[CHAPTER]
TIMEBASE=1/44100
START=1420164096
END=1483602944
title=Chapter 36
[CHAPTER]
TIMEBASE=1/44100
START=1483602944
END=1559736320
title=Chapter 37
[CHAPTER]
TIMEBASE=1/44100
START=1559736320
END=1610887168
title=Chapter 38
[CHAPTER]
TIMEBASE=1/44100
START=1610887168
END=1679741952
title=Chapter 39
[CHAPTER]
TIMEBASE=1/44100
START=1679741952
END=1700992000
title=Chapter 40
[CHAPTER]
TIMEBASE=1/44100
START=1700992000
END=1865101312
title=Chapter 41
[CHAPTER]
TIMEBASE=1/44100
START=1865101312
END=1923177472
title=Chapter 42
[CHAPTER]
TIMEBASE=1/44100
START=1923177472
END=2012560384
title=Chapter 43
[CHAPTER]
TIMEBASE=1/44100
START=2012560384
END=2087543808
title=Chapter 44
[CHAPTER]
TIMEBASE=1/44100
START=2087543808
END=2158842880
title=Chapter 45
[CHAPTER]
TIMEBASE=1/44100
START=2158842880
END=2242908160
title=Chapter 46
[CHAPTER]
TIMEBASE=1/44100
START=2242908160
END=2318816256
title=Chapter 47
[CHAPTER]
TIMEBASE=1/44100
START=2318816256
END=2363648000
title=Chapter 48
[CHAPTER]
TIMEBASE=1/44100
START=2363648000
END=2429690880
title=Chapter 49
[CHAPTER]
TIMEBASE=1/44100
START=2429690880
END=2462408704
title=Chapter 50
[CHAPTER]
TIMEBASE=1/44100
START=2462408704
END=2596473054
title=Chapter 51

```

```
;FFMETADATA1
major_brand=aax 
minor_version=1
compatible_brands=aax M4B mp42isom
date=2010
comment=Chapter 51
title=The Many-Colored Land: Volume 1 of the Saga of Pliocene Exile
artist=Julian May
album_artist=Julian May
album=The Many-Colored Land: Volume 1 of the Saga of Pliocene Exile
genre=Audiobook
copyright=©1981 Julian May (P)2010 Blackstone Audio, Inc.
encoder=Lavf59.16.100
[CHAPTER]
TIMEBASE=1/1000
START=0
END=3924
title=Intro
[CHAPTER]
TIMEBASE=1/1000
START=3924
END=888092
title=Opening Credits
[CHAPTER]
TIMEBASE=1/1000
START=888092
END=1897393
title=Prologue
[CHAPTER]
TIMEBASE=1/1000
START=1897393
END=1900393
title=The Leavetaking
[CHAPTER]
TIMEBASE=1/1000
START=15484423
END=15487423
title=The Initiation
[CHAPTER]
TIMEBASE=1/1000
START=38571226
END=38569281
title=The Alliance
[CHAPTER]
TIMEBASE=1/1000
START=58872009
END=58876954
title=Outro

```

**Comment by PurpleBooth** [comment] 2022-06-23 07:58
I would appreciate some feedback on the PR. I think I have it, however I am not familiar with the format of the FFMETADATA1, so I could do with some thoughts on if the timestamps are correctly lined up

**Comment by PurpleBooth** [comment] 2022-06-23 08:24
The above PR seems to set things up right

**Comment by mkb79** [comment] 2022-06-23 11:05
Thank you for helping me out. I've merged all your PR now!

**Closed** 2022-06-24 21:23 UTC
